header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Canonical Ltd.
    content: |
      Copyright [year] [owner]
      See LICENSE file for licensing details.
    pattern: |
        Copyright \d{4} Canonical Ltd.
        See LICENSE file for licensing details.
  paths:
    - '**'
  paths-ignore:
    - '.github/**'
    - '**/*.json'
    - '**/*.md'
    - '**/*.txt'
    - '.jujuignore'
    - '.gitignore'
    - '.licenserc.yaml'
    - 'CODEOWNERS'
    - 'LICENSE'
    - 'trivy.yaml'
    - 'pyproject.toml'
    - 'zap_rules.tsv'
    - '**/*.md.j2'
  comment: on-failure
